//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaNews.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actor_Movie_Mapping
    {
        public int Mapping_ID { get; set; }
        public Nullable<int> Actor_Id { get; set; }
        public Nullable<int> Movie_Id { get; set; }
    
        public virtual Actor tblActor { get; set; }
        public virtual Movie tblMovie { get; set; }
    }
}
